### PR TITLE
Closes #94 - Fix KadaiProducersTest, refactor ExampleBootstrapTest

### LINKED ISSUE #94: The test KadaiProducersTest is red when building locally
On developers' computers, this test does not work and hinders the local build.

### PR DESCRIPTION
**Pull request by CRoberto1926**
### Thanks for your PR! Please fill out the following list :)

---

- [x] I put the ticket or multiple tickets in review
- [x] Commit message format → Closes #&lt;Issue Number&gt; - Your commit message.
- [x] Sonarcloud link : https://sonarcloud.io/summary/new_code?id=CRoberto1926_kadai&branch=bugfix%2Fissue-94-kadai-producers-test-fix
- [x] No documentation update needed
- [ ] Link to PR with documentation update: \<add the link here>
- [x] No Release Notes needed
- [ ] Release Notes :

```

```

### CODE REVIEW

File: lib/kadai-cdi/src/test/java/io/kadai/common/internal/KadaiProducersTest.java [hunk 1]
```diff
@@ -86,16 +90,8 @@ public static Archive<?> createDeployment() throws Exception {
     deployment.addAsModule(webArchive);
 
     deployment.addAsManifestResource("META-INF/beans.xml", "beans.xml");
-    return deployment;
-  }
 
-  @BeforeClass
```
Comment (ryzheboka) [inline lib/kadai-cdi/src/test/java/io/kadai/common/internal/KadaiProducersTest.java:92]: Why did moving this into createDeployment fix flakiness?

File: lib/kadai-cdi-example/src/test/java/io/kadai/example/ExampleBootstrapTest.java [hunk 2]
```diff
@@ -67,39 +65,13 @@ public static Archive<?> createDeployment() throws Exception {
     deployment.addAsModule(ejbModule);
 
     deployment.addAsManifestResource("META-INF/beans.xml", "beans.xml");
-    return deployment;
-  }
 
-  @BeforeClass
-  public static void cleanKadaiH2DataFolder() throws IOException {
```
Comment (ryzheboka) [inline lib/kadai-cdi-example/src/test/java/io/kadai/example/ExampleBootstrapTest.java:74]: Why did you move this into createDeployment?

File: lib/kadai-cdi-example/src/test/java/io/kadai/example/ExampleBootstrapTest.java [hunk 3]
```diff
@@ -67,39 +65,13 @@ public static Archive<?> createDeployment() throws Exception {
...
-    Path kadaiH2Data = Path.of(System.getProperty("user.home"), "kadai-h2-data");
-    if (Files.exists(kadaiH2Data)) {
-      FileUtils.forceDelete(kadaiH2Data.toFile());
-    }
+    return deployment;
   }
 
   @Test
   public void should_count_tasks_after_example_cdi_application_was_deployed() throws Exception {
-    // this test method is started that fast that the commit
```
Comment (ryzheboka) [inline lib/kadai-cdi-example/src/test/java/io/kadai/example/ExampleBootstrapTest.java:84]: Is the problem mentioned in the comment not relevant anymore?

**Review by ryzheboka — APPROVED** [review]
