### PR TITLE
Closes #47 - Fix flakiness of some tests

### LINKED ISSUE #47: Flaky Tests
The test ServiceLevelPriorityWithWorkingDaysCalculationAccTest.should_VerifyThatCreateAndPlannedAreClose failed in the pipeline two times consecutevely. After that and before that, the test never failed. It might be related to the usage of Instant.now()

The test should_DeleteOldWorkbasketCleanupJobs_When_InitializingSchedule is also flaky. It needs to be looked into

KadaiProducersTest.testRollback is also flaky

ExampleBootstrapTest.should_count_tasks_after_example_cdi_application_was_deployed is also flaky

### PR DESCRIPTION
**Pull request by CRoberto1926**
### Thanks for your PR! Please fill out the following list :)

---

- [x] I put the ticket or multiple tickets in review
- [x] Commit message format → Closes #&lt;Issue Number&gt; - Your commit message.
- [x] Sonarcloud link : https://sonarcloud.io/summary/new_code?id=CRoberto1926_kadai&branch=bugfix%2Fissue-47-flaky-tests
- [x] No documentation update needed
- [ ] Link to PR with documentation update: \<add the link here>
- [x] No Release Notes needed
- [ ] Release Notes :

```

```

### CODE REVIEW

File: lib/kadai-core-test/src/test/java/acceptance/jobs/AbstractKadaiJobAccTest.java [hunk 1]
```diff
@@ -109,11 +108,13 @@ void should_SetNextScheduledJobBasedOnDueDateOfPredecessor_When_RunningTaskClean
   @WithAccessId(user = "admin")
   @TestFactory
   Stream<DynamicTest> should_DeleteOldCleanupJobs_When_InitializingSchedule() {
+
```
Comment (ryzheboka) [inline lib/kadai-core-test/src/test/java/acceptance/jobs/AbstractKadaiJobAccTest.java]: Why did you add an empty line here?

File: lib/kadai-core/src/test/java/acceptance/task/ServiceLevelPriorityWithWorkingDaysCalculationAccTest.java [hunk 2]
```diff
@@ -184,6 +185,26 @@ void should_VerifyThatCreateAndPlannedAreClose() throws Exception {
     assertThat(createdTask.getPlanned()).isEqualTo(planned);
     assertThat(createdTask.getCreated()).isBefore(createdTask.getPlanned());
 
+    LocalDate localDateNow =
+        LocalDate.ofInstant(now, kadaiConfiguration.getWorkingTimeScheduleTimeZone());
+    LocalDate localDateInTwoHours =
+        LocalDate.ofInstant(inTwoHours, kadaiConfiguration.getWorkingTimeScheduleTimeZone());
+
+    if (!localDateNow.isEqual(localDateInTwoHours)
```
Comment (ryzheboka) [inline lib/kadai-core/src/test/java/acceptance/task/ServiceLevelPriorityWithWorkingDaysCalculationAccTest.java:193]: Do you think it's better to work with a fixed date instead of now? This way, we won't need to check if now lies between 22:00:00 and 23:59:59 of a working day that precedes a non working day

**Review by ryzheboka — CHANGES_REQUESTED** [review]

File: lib/kadai-core-test/src/test/java/acceptance/jobs/AbstractKadaiJobAccTest.java (hunk 1 above)
Comment (CRoberto1926) [reply lib/kadai-core-test/src/test/java/acceptance/jobs/AbstractKadaiJobAccTest.java]: There isn't a particular reason, sometimes I find more readable to have an empty line between the method declaration and the first line of code in the method. Do you want me to delete this empty line?

File: lib/kadai-core/src/test/java/acceptance/task/ServiceLevelPriorityWithWorkingDaysCalculationAccTest.java (hunk 2 above)
Comment (CRoberto1926) [reply lib/kadai-core/src/test/java/acceptance/task/ServiceLevelPriorityWithWorkingDaysCalculationAccTest.java:193]: Yes, that was also my first idea. Unfortunately, the TaskService.createTask() method sets the created property of a task to the Instant in which the task is created, so we would need to modify that code (see TaskServiceImpl.standardSettingsOnTaskCreation()).

Comment (CRoberto1926) [reply lib/kadai-core/src/test/java/acceptance/task/ServiceLevelPriorityWithWorkingDaysCalculationAccTest.java:193]: I guess that we don't want to modify TaskServiceImpl for this test...

File: lib/kadai-core-test/src/test/java/acceptance/jobs/AbstractKadaiJobAccTest.java (hunk 1 above)
Comment (ryzheboka) [reply lib/kadai-core-test/src/test/java/acceptance/jobs/AbstractKadaiJobAccTest.java]: Yes

File: lib/kadai-core/src/test/java/acceptance/task/ServiceLevelPriorityWithWorkingDaysCalculationAccTest.java (hunk 2 above)
Comment (ryzheboka) [reply lib/kadai-core/src/test/java/acceptance/task/ServiceLevelPriorityWithWorkingDaysCalculationAccTest.java:193]: We definitly don't want to mondify productive code for a test. Could you use TaskImpl.setCreated method in the test after creation?

File: lib/kadai-core-test/src/test/java/acceptance/jobs/AbstractKadaiJobAccTest.java (hunk 1 above)
Comment (CRoberto1926) [reply lib/kadai-core-test/src/test/java/acceptance/jobs/AbstractKadaiJobAccTest.java]: done

File: lib/kadai-core/src/test/java/acceptance/task/ServiceLevelPriorityWithWorkingDaysCalculationAccTest.java (hunk 2 above)
Comment (CRoberto1926) [reply lib/kadai-core/src/test/java/acceptance/task/ServiceLevelPriorityWithWorkingDaysCalculationAccTest.java:193]: Yes, we could. But what would be the advantage to it? Isn't it the same as skipping the assertion?

**Review by ryzheboka — APPROVED** [review]
