### PR TITLE
Closes #922: Fix unintentionally duplicated tests or remove them

### LINKED ISSUE #922: Fix unintentionally duplicated tests or remove them
Some implementations are duplicate for tests.
Apart from #635 where the reason is an unsufficient `@WithAccessId`, there appear to be cases where a test was copied, it's name was changed but it's implementation not.
Highly likely to be a dev error.

Either adjust according to the nam or remove.

So far i found:
- https://sonarcloud.io/project/issues?cleanCodeAttributeCategories=ADAPTABLE&impactSeverities=MEDIUM&issueStatuses=OPEN%2CCONFIRMED&id=kadai-io_kadai&open=AZIkJlo-YafQhmhKcd-e&tab=code
- https://sonarcloud.io/project/issues?cleanCodeAttributeCategories=ADAPTABLE&impactSeverities=MEDIUM&issueStatuses=OPEN%2CCONFIRMED&id=kadai-io_kadai&open=AZIkJlpKYafQhmhKcd-i

### PR DESCRIPTION
**Pull request by jamesrdi**
## Definition of Done

- [x] The corresponding ticket is in state `In Review`
- [x] The corresponding ticket is attached to this Pull-Request
- [x] The commit-message-format `Closes #ISSUE_ID - PROBLEM/SOLUTION` 
  - is present as single-commit already or
  - will be squashed on merge
- [x] The changes pass the SonarQubeCloud-Quality-Gate
- [x] If the documentation needs an update, following there's a link to it:

### CODE REVIEW

File: lib/kadai-core-test/src/test/java/acceptance/task/reopen/ReopenTaskAccTest.java [hunk 1]
```diff
@@ -167,15 +167,13 @@ void should_ReopenTask_For_NonFinalEndState(TaskState state) throws Exception {
...
 
-    assertThat(reopenedTask)
-        .isNotNull()
-        .extracting(Task::getState).isEqualTo(TaskState.CLAIMED);
+    assertThat(reopenedTask).isNotNull().extracting(Task::getState).isEqualTo(TaskState.CLAIMED);
   }
 
   @ParameterizedTest
-  @MethodSource("provideFinalStates")
+  @MethodSource("provideInvalidStates")
```
Comment (jamesrdi) [inline lib/kadai-core-test/src/test/java/acceptance/task/reopen/ReopenTaskAccTest.java:174]: Here is the actual change

File: lib/kadai-core-test/src/test/java/acceptance/task/reopen/ReopenTaskAccTest.java [hunk 2]
```diff
@@ -514,6 +477,10 @@ private static Stream<Arguments> provideNonEndStates() {
     return Arrays.stream(EnumUtil.allValuesExceptFor(TaskState.END_STATES)).map(Arguments::of);
   }
 
+  private static Stream<Arguments> provideInvalidStates() {
```
Comment (jamesrdi) [inline lib/kadai-core-test/src/test/java/acceptance/task/reopen/ReopenTaskAccTest.java:480]: Here is the actual change

**Comment by jamesrdi** [comment]
This PR contains also changes from the update of copyright headers and also formatting

**Comment by leantios** [comment]
Is this ready for review?

**Comment by bruderj15** [comment]
Can this be reviewed?
If yes, check all boxes and request a review.

**Comment by jamesrdi** [comment]
> Can this be reviewed? If yes, check all boxes and request a review.

Yes, sorry if it was unclear. I only found one test where there is duplication, I filtered in the sonarqube according to the duplicate tag:
https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&tags=duplicate&id=kadai-io_kadai

**Review by bruderj15 — APPROVED** [review]

**Comment by bruderj15** [comment]
@jamesrdi Reminder to merge this :)
