### PR TITLE
Closes #1121 - Fix exception handling in task distribution

### LINKED ISSUE #1121: Fix Bug in Task Distribution
When distributing multiple tasks, it can happen that some tasks cause issues. In the transferTasks method, this meant that the remaining tasks were successfully transferred, and a result was returned that included the problematic tasks along with the corresponding exceptions. In contrast, the new distributeTasks method aborts the entire operation. Specifically, this concerns the TaskNotFoundException. The new behavior could lead to significant delays in operations and/or increased effort.

Bug refers to: https://github.com/kadai-io/kadai/issues/372

### PR DESCRIPTION
**Pull request by jannikFuellgrafEnvite**
## Definition of Done

- [x] The corresponding ticket is in state `In Review`
- [x] The corresponding ticket is attached to this Pull-Request
- [x] The commit-message-format `Closes #ISSUE_ID - PROBLEM/SOLUTION` 
  - is present as single-commit already or
  - will be squashed on merge
- [x] The changes pass the SonarQubeCloud-Quality-Gate
- [ ] If the documentation needs an update, following there's a link to it:

### CODE REVIEW

File: lib/kadai-core/src/main/java/io/kadai/task/internal/TaskDistributor.java [hunk 1]
```diff
@@ -170,7 +154,7 @@ private BulkOperationResults<String, KadaiException> distributeTasks(
 
       workbasketService.checkAuthorization(sourceWorkbasketId, WorkbasketPermission.DISTRIBUTE);
 
-      taskIds = resolveTaskIds(sourceWorkbasketId, taskIds);
+      taskIds = resolveTaskIds(sourceWorkbasketId, taskIds, operationResults);
```
Comment (bruderj15) [inline lib/kadai-core/src/main/java/io/kadai/task/internal/TaskDistributor.java]: Instead of this C++ Multi-Return-Value approach I'd personally favor a more functional one, returning a `Pair<List<String>, BulkOperationResults<String, KadaiException>>`.
This significantly reduces cognitive load.

Similar to `transferTasks(newTaskDistribution, taskTransferFlags, operationResults);` a few lines down.
Instead of returning `void` it should really return the `operationResults` - you then merge them afterwards.

File: lib/kadai-core/src/main/java/io/kadai/task/internal/TaskDistributor.java [hunk 2]
```diff
@@ -160,8 +145,7 @@ private BulkOperationResults<String, KadaiException> distributeTasks(
       Map<String, Object> additionalInformation)
       throws InvalidArgumentException,
           NotAuthorizedOnWorkbasketException,
-          WorkbasketNotFoundException,
-          TaskNotFoundException {
+          WorkbasketNotFoundException {
 
     BulkOperationResults<String, KadaiException> operationResults = new BulkOperationResults<>();
```
Comment (bruderj15) [inline lib/kadai-core/src/main/java/io/kadai/task/internal/TaskDistributor.java]: Reader might wonder why this needs to live outside the try-catch-block.

**Review by bruderj15 — COMMENTED** [review]
Help me with the desired behavior:
- Partial failure for non-existing tasks
- Entire failure for non-existing workbaskets?

If the latter is actually desired, revisit `transferTasks()`.
It currently wraps the `WorkbasketNotFoundException` inside the `BulkOperationResults`.

**Review by bruderj15 — APPROVED** [review]
