### PR TITLE
Closes #934 - Remove duplicate flaky test

### LINKED ISSUE #934: Extremely flaky test fails >80% of the time in CI
[UpdateClassificationAccTest.should_SetFieldsCorrectly_When_TryingToUpdateClassification](https://github.com/kadai-io/kadai/actions/runs/14762593954/job/41446917082?pr=676#step:7:3928) fails insanely often recently.

### PR DESCRIPTION
**Pull request by bruderj15**
## Definition of Done

- [x] The corresponding ticket is in state `In Review`
- [x] The corresponding ticket is attached to this Pull-Request
- [x] The commit-message-format `Closes #ISSUE_ID - PROBLEM/SOLUTION` 
  - is present as single-commit already or
  - will be squashed on merge
- [x] The changes pass the SonarQubeCloud-Quality-Gate
- [x] If the documentation needs an update, following there's a link to it:

### CODE REVIEW

**Comment by bruderj15** [comment]
@leantios this succeeded the test for every job on the first try (very promising)

File: lib/kadai-core-test/src/test/java/acceptance/classification/update/UpdateClassificationWithWorkingDayCalculatorAccTest.java [hunk 1]
```diff
@@ -150,7 +150,7 @@ void should_SetFieldsCorrectly_When_TryingToUpdateClassification() throws Except
     expectedClassification.setId(updatedClassification.getId());
 
     assertThat(expectedClassification).hasNoNullFieldsOrProperties();
-    assertThat(modifiedBefore).isBefore(classification.getModified());
+    assertThat(modifiedBefore).isBefore(updatedClassification.getModified());
```
Comment (leantios) [inline lib/kadai-core-test/src/test/java/acceptance/classification/update/UpdateClassificationWithWorkingDayCalculatorAccTest.java:153]: This seems to help with the flakiness but I really don't understand why. In the [`ClassificationService`](https://github.com/kadai-io/kadai/blob/eec8030ee3153a8819b90ff1c5bf003aa481c683/lib/kadai-core/src/main/java/io/kadai/classification/internal/ClassificationServiceImpl.java#L297), the timestamp of `classification` is updated. The only difference is that `updatedClassification` is read out from the database.

Comment (bruderj15) [reply lib/kadai-core-test/src/test/java/acceptance/classification/update/UpdateClassificationWithWorkingDayCalculatorAccTest.java:153]: Sometimes even the magician doesn't understand his own trick

**Review by leantios — APPROVED** [review]
