### PR TITLE
Closes #162 - Fix some SonarCloud issues in Backend

### LINKED ISSUE #162: Fix SonarCloud issues in Backend

### PR DESCRIPTION
**Pull request by CRoberto1926**
### Thanks for your PR! Please fill out the following list :)

---

- [x] I put the ticket or multiple tickets in review
- [x] Commit message format → Closes #&lt;Issue Number&gt; - Your commit message.
- [x] Sonarcloud link : https://sonarcloud.io/summary/new_code?id=CRoberto1926_kadai&branch=chore%2Fsonarcloud-fixes
- [x] No documentation update needed
- [ ] Link to PR with documentation update: \<add the link here>
- [x] No Release Notes needed
- [ ] Release Notes :

```

```

### CODE REVIEW

File: history/kadai-simplehistory-provider/src/main/java/io/kadai/simplehistory/impl/TaskHistoryQueryImpl.java [hunk 1]
```diff
@@ -674,7 +667,7 @@ public List<TaskHistoryEvent> list(int offset, int limit) {
   @Override
   public List<String> listValues(
       TaskHistoryQueryColumnName dbColumnName, SortDirection sortDirection) {
-    List<String> result = new ArrayList<>();
+    List<String> result;
```
Comment (ryzheboka) [inline history/kadai-simplehistory-provider/src/main/java/io/kadai/simplehistory/impl/TaskHistoryQueryImpl.java]: Why do we need to declare result at all? It's only returned if result = internalKadaiEngine.getSqlSession().selectList(LINK_TO_VALUE_MAPPER, this); is executed successfully.

File: history/kadai-simplehistory-provider/src/main/java/io/kadai/simplehistory/impl/WorkbasketHistoryQueryImpl.java [hunk 2]
```diff
@@ -517,7 +511,7 @@ public List<WorkbasketHistoryEvent> list(int offset, int limit) {
   @Override
   public List<String> listValues(
       WorkbasketHistoryQueryColumnName dbColumnName, SortDirection sortDirection) {
-    List<String> result = new ArrayList<>();
+    List<String> result;
```
Comment (ryzheboka) [inline history/kadai-simplehistory-provider/src/main/java/io/kadai/simplehistory/impl/WorkbasketHistoryQueryImpl.java]: Why do we need to declare result at all? It's only returned if result = internalKadaiEngine.getSqlSession().selectList(LINK_TO_VALUE_MAPPER, this); is executed successfully.

File: history/kadai-simplehistory-provider/src/test/java/acceptance/events/workbasket/CreateHistoryEventOnWorkbasketMarkedForDeletionAccTest.java [hunk 3]
```diff
@@ -60,7 +60,7 @@ void should_CreateWorkbasketMarkedForDeletionHistoryEvent_When_WorkbasketIsMarke
 
     String eventType = events.get(0).getEventType();
     String eventWorkbasketId = events.get(0).getWorkbasketId();
-    String details = workbasketHistoryEventMapper.findById(events.get(0).getId()).getDetails();
+    workbasketHistoryEventMapper.findById(events.get(0).getId());
```
Comment (ryzheboka) [inline history/kadai-simplehistory-provider/src/test/java/acceptance/events/workbasket/CreateHistoryEventOnWorkbasketMarkedForDeletionAccTest.java]: Why do we need this line? Could we check the value of "details" instead of deleting the variable?

File: history/kadai-simplehistory-provider/src/main/java/io/kadai/simplehistory/impl/TaskHistoryQueryImpl.java (hunk 1 above)
Comment (CRoberto1926) [reply history/kadai-simplehistory-provider/src/main/java/io/kadai/simplehistory/impl/TaskHistoryQueryImpl.java]: done

File: history/kadai-simplehistory-provider/src/main/java/io/kadai/simplehistory/impl/WorkbasketHistoryQueryImpl.java (hunk 2 above)
Comment (CRoberto1926) [reply history/kadai-simplehistory-provider/src/main/java/io/kadai/simplehistory/impl/WorkbasketHistoryQueryImpl.java]: done

File: history/kadai-simplehistory-provider/src/test/java/acceptance/events/workbasket/CreateHistoryEventOnWorkbasketMarkedForDeletionAccTest.java (hunk 3 above)
Comment (CRoberto1926) [reply history/kadai-simplehistory-provider/src/test/java/acceptance/events/workbasket/CreateHistoryEventOnWorkbasketMarkedForDeletionAccTest.java]: I don't want to change any logic or tests in this PR. I deleted the line altogether

File: history/kadai-simplehistory-rest-spring/src/test/java/io/kadai/simplehistory/rest/TaskHistoryEventControllerIntTest.java [hunk 4]
```diff
@@ -54,11 +53,11 @@ class TaskHistoryEventControllerIntTest {
 
   private static final ParameterizedTypeReference<TaskHistoryEventPagedRepresentationModel>
       TASK_HISTORY_EVENT_PAGED_REPRESENTATION_MODEL_TYPE =
-          new ParameterizedTypeReference<TaskHistoryEventPagedRepresentationModel>() {};
+          new ParameterizedTypeReference<>() {};
 
   private static final ParameterizedTypeReference<TaskHistoryEventRepresentationModel>
       TASK_HISTORY_EVENT_REPRESENTATION_MODEL_TYPE =
-          new ParameterizedTypeReference<TaskHistoryEventRepresentationModel>() {};
```
Comment (ryzheboka) [inline history/kadai-simplehistory-rest-spring/src/test/java/io/kadai/simplehistory/rest/TaskHistoryEventControllerIntTest.java:61]: Why did you delete the type?

File: history/kadai-simplehistory-rest-spring/src/test/java/io/kadai/simplehistory/rest/TaskHistoryEventControllerIntTest.java [hunk 5]
```diff
@@ -54,11 +53,11 @@ class TaskHistoryEventControllerIntTest {
 
   private static final ParameterizedTypeReference<TaskHistoryEventPagedRepresentationModel>
       TASK_HISTORY_EVENT_PAGED_REPRESENTATION_MODEL_TYPE =
-          new ParameterizedTypeReference<TaskHistoryEventPagedRepresentationModel>() {};
+          new ParameterizedTypeReference<>() {};
```
Comment (ryzheboka) [inline history/kadai-simplehistory-rest-spring/src/test/java/io/kadai/simplehistory/rest/TaskHistoryEventControllerIntTest.java:56]: Why did you delete the type?

File: lib/kadai-core-test/src/test/java/acceptance/PojoTest.java [hunk 6]
```diff
@@ -45,26 +44,26 @@
 /** check classes with a custom equals and hashcode implementation for correctness. */
 class PojoTest {
 
-  private static final List<Class<?>> POJO_CLASSES = getPojoClasses();
-
-  private static List<Class<?>> getPojoClasses() {
-    // TODO how to identify pojos? Is overwritten equals method enough?
```
Comment (ryzheboka) [inline lib/kadai-core-test/src/test/java/acceptance/PojoTest.java:51]: Why did you delete the TODO?

File: lib/kadai-core/src/main/java/io/kadai/common/api/SharedConstants.java [hunk 7]
```diff
@@ -19,5 +19,9 @@
 package io.kadai.common.api;
 
 public class SharedConstants {
-  public static String MASTER_DOMAIN = "";
+
+  private SharedConstants() {
```
Comment (ryzheboka) [inline lib/kadai-core/src/main/java/io/kadai/common/api/SharedConstants.java:23]: Why did you add this constructor?

File: history/kadai-simplehistory-rest-spring/src/test/java/io/kadai/simplehistory/rest/TaskHistoryEventControllerIntTest.java (hunk 4 above)
Comment (CRoberto1926) [reply history/kadai-simplehistory-rest-spring/src/test/java/io/kadai/simplehistory/rest/TaskHistoryEventControllerIntTest.java:61]: Because the compiler infers it automatically: https://docs.oracle.com/javase/7/docs/technotes/guides/language/type-inference-generic-instance-creation.html

File: history/kadai-simplehistory-rest-spring/src/test/java/io/kadai/simplehistory/rest/TaskHistoryEventControllerIntTest.java (hunk 5 above)
Comment (CRoberto1926) [reply history/kadai-simplehistory-rest-spring/src/test/java/io/kadai/simplehistory/rest/TaskHistoryEventControllerIntTest.java:56]: Because the compiler infers it automatically: https://docs.oracle.com/javase/7/docs/technotes/guides/language/type-inference-generic-instance-creation.html

File: lib/kadai-core-test/src/test/java/acceptance/PojoTest.java (hunk 6 above)
Comment (CRoberto1926) [reply lib/kadai-core-test/src/test/java/acceptance/PojoTest.java:51]: Is it ever going to be taken care of? :)

File: lib/kadai-core/src/main/java/io/kadai/common/api/SharedConstants.java (hunk 7 above)
Comment (CRoberto1926) [reply lib/kadai-core/src/main/java/io/kadai/common/api/SharedConstants.java:23]: Because the class clearly must not be instantiated, and an empty private constructor overwrites the default one, which is public.

File: lib/kadai-core/src/main/java/io/kadai/spi/history/internal/HistoryEventManager.java [hunk 8]
```diff
@@ -52,29 +53,36 @@ public boolean isEnabled() {
...
+          LogSanitizer.stripLineBreakingChars(event));
     }
     kadaiHistories.forEach(CheckedConsumer.wrap(historyProvider -> historyProvider.create(event)));
   }
 
   public void createEvent(ClassificationHistoryEvent event) {
     if (LOGGER.isDebugEnabled()) {
-      LOGGER.debug("Sending event to history service providers: {}", event);
+      LOGGER.debug(
+          "Sending {} to history service providers: {}", event.getClass().getSimpleName(), event);
```
Comment (ryzheboka) [inline lib/kadai-core/src/main/java/io/kadai/spi/history/internal/HistoryEventManager.java:75]: Why did you add another parameter?

File: lib/kadai-core/src/main/java/io/kadai/spi/history/internal/HistoryEventManager.java [hunk 9]
```diff
@@ -52,29 +53,36 @@ public boolean isEnabled() {
...
     }
     kadaiHistories.forEach(CheckedConsumer.wrap(historyProvider -> historyProvider.create(event)));
   }
 
   public void createEvent(WorkbasketHistoryEvent event) {
     if (LOGGER.isDebugEnabled()) {
-      LOGGER.debug("Sending event to history service providers: {}", event);
+      LOGGER.debug(
+          "Sending {} to history service providers: {}",
```
Comment (ryzheboka) [inline lib/kadai-core/src/main/java/io/kadai/spi/history/internal/HistoryEventManager.java:65]: Why did you add another parameter?

File: lib/kadai-core/src/main/java/io/kadai/spi/history/internal/HistoryEventManager.java [hunk 10]
```diff
@@ -52,29 +53,36 @@ public boolean isEnabled() {
 
   public void createEvent(TaskHistoryEvent event) {
     if (LOGGER.isDebugEnabled()) {
-      LOGGER.debug("Sending event to history service providers: {}", event);
+      LOGGER.debug(
+          "Sending {} to history service providers: {}", event.getClass().getSimpleName(), event);
```
Comment (ryzheboka) [inline lib/kadai-core/src/main/java/io/kadai/spi/history/internal/HistoryEventManager.java:57]: Why did you add another parameter?

File: lib/kadai-core/src/main/java/io/kadai/task/internal/models/TaskImpl.java [hunk 11]
```diff
@@ -316,14 +317,19 @@ public TaskSummary asSummary() {
 
   @Override
   public Attachment removeAttachment(String attachmentId) {
-    Attachment result = null;
-    for (Attachment attachment : attachments) {
-      if (attachment.getId().equals(attachmentId) && attachments.remove(attachment)) {
-        result = attachment;
-        break;
-      }
+
```
Comment (ryzheboka) [inline lib/kadai-core/src/main/java/io/kadai/task/internal/models/TaskImpl.java:320]: Do we need to agree if we want to add an empty line in the beginning of the methods? We don't do it at the moment

File: lib/kadai-core/src/main/java/io/kadai/user/internal/UserServiceImpl.java [hunk 12]
```diff
@@ -161,17 +161,20 @@ public User updateUser(User userToUpdate)
   @Override
   public void deleteUser(String id)
       throws UserNotFoundException, InvalidArgumentException, NotAuthorizedException {
+
     internalKadaiEngine.getEngine().checkRoleMembership(KadaiRole.BUSINESS_ADMIN, KadaiRole.ADMIN);
-    getUser(id);
+
+    User user = getUser(id);
+    String userId = user.getId();
```
Comment (ryzheboka) [inline lib/kadai-core/src/main/java/io/kadai/user/internal/UserServiceImpl.java:168]: Isn't userId same as id? Why did you add this variable?

File: lib/kadai-core/src/test/java/acceptance/jobs/JobRunnerAccTest.java [hunk 13]
```diff
@@ -76,13 +72,6 @@ void should_onlyExecuteJobOnce_When_MultipleThreadsTryToRunJobsAtTheSameTime() t
                 KadaiEngine.buildKadaiEngine(
                     kadaiConfiguration, ConnectionManagementMode.AUTOCOMMIT);
             DataSource dataSource = DataSourceGenerator.getDataSource();
-            // We have to slow down the transaction.
```
Comment (ryzheboka) [inline lib/kadai-core/src/test/java/acceptance/jobs/JobRunnerAccTest.java:79]: Have you checked if the comment is relevant?

File: lib/kadai-core/src/test/java/acceptance/task/query/QueryTasksAccTest.java [hunk 14]
```diff
@@ -370,7 +371,7 @@ Stream<DynamicTest> should_ReturnCorrectResults_When_QueryingForCustomXStatement
               Triplet.of(TaskCustomField.CUSTOM_4, new String[] {"%ust%", "%ty"}, 2),
               Triplet.of(TaskCustomField.CUSTOM_5, new String[] {"ew", "al"}, 6),
               Triplet.of(TaskCustomField.CUSTOM_6, new String[] {"%custom6%", "%vvg%", "11%"}, 5),
-              Triplet.of(TaskCustomField.CUSTOM_7, new String[] {"ijk%"}, 1),
+              Triplet.of(CUSTOM_7, new String[] {"ijk%"}, 1),
```
Comment (ryzheboka) [inline lib/kadai-core/src/test/java/acceptance/task/query/QueryTasksAccTest.java]: Why did you change it here but not everywhere else?

File: lib/kadai-core/src/test/java/acceptance/task/query/QueryTasksAccTest.java [hunk 15]
```diff
@@ -415,7 +416,7 @@ Stream<DynamicTest> should_ReturnCorrectResults_When_QueryingForCustomXNotIn() {
               Triplet.of(TaskCustomField.CUSTOM_4, new String[] {""}, 2),
               Triplet.of(TaskCustomField.CUSTOM_5, new String[] {"ew", "al", "el"}, 93),
               Triplet.of(TaskCustomField.CUSTOM_6, new String[] {"11", "vvg"}, 96),
-              Triplet.of(TaskCustomField.CUSTOM_7, new String[] {"custom7", "ijk"}, 98),
+              Triplet.of(CUSTOM_7, new String[] {"custom7", "ijk"}, 98),
```
Comment (ryzheboka) [inline lib/kadai-core/src/test/java/acceptance/task/query/QueryTasksAccTest.java]: Why did you change it here but not everywhere else?

File: lib/kadai-core/src/test/java/acceptance/task/update/UpdateTaskAttachmentWithWorkingDaysCalculationAccTest.java [hunk 16]
```diff
@@ -321,15 +321,15 @@ void testUpdateAttachment() throws Exception {
     assertThat(task.getPriority()).isEqualTo(1);
     assertThat(task.getPlanned().plus(Duration.ofDays(1))).isEqualTo(task.getDue());
 
-    Attachment attachment = this.attachment;
-    task.addAttachment(attachment);
+    Attachment attachmentImpl = this.attachment;
```
Comment (ryzheboka) [inline lib/kadai-core/src/test/java/acceptance/task/update/UpdateTaskAttachmentWithWorkingDaysCalculationAccTest.java]: Why is it now called attachmentImpl, although the type is not AttachmentImpl but Attachment?

File: rest/kadai-rest-spring/src/main/java/io/kadai/task/rest/assembler/AttachmentRepresentationModelAssembler.java [hunk 17]
```diff
@@ -65,7 +62,6 @@ public AttachmentRepresentationModel toModel(@NonNull Attachment attachment) {
     repModel.setObjectReference(objectReferenceAssembler.toModel(attachment.getObjectReference()));
     repModel.setChannel(attachment.getChannel());
     repModel.setCustomAttributes(attachment.getCustomAttributeMap());
-    repModel.add(linkTo(AttachmentController.class).slash(attachment.getId()).withSelfRel());
```
Comment (ryzheboka) [inline rest/kadai-rest-spring/src/main/java/io/kadai/task/rest/assembler/AttachmentRepresentationModelAssembler.java:68]: Why did you delete this?

File: rest/kadai-rest-spring-example-wildfly/src/test/java/io/kadai/example/wildfly/KadaiWildflyWithHistoryLoggerEnabledTest.java [hunk 18]
```diff
@@ -61,17 +55,6 @@ public static Archive<?> createTestArchive() {
     LOGGER.info(
         "Running with db.type '{}' and using property file '{}'", dbType, applicationPropertyFile);
 
-    MavenCoordinate historyLoggerCoordinate =
```
Comment (ryzheboka) [inline rest/kadai-rest-spring-example-wildfly/src/test/java/io/kadai/example/wildfly/KadaiWildflyWithHistoryLoggerEnabledTest.java:64]: Why were historyLoggerCoordinate and historyLoggerDependency initialized here?

**Review by ryzheboka — CHANGES_REQUESTED** [review]

File: lib/kadai-core/src/main/java/io/kadai/spi/history/internal/HistoryEventManager.java (hunk 8 above)
Comment (CRoberto1926) [reply lib/kadai-core/src/main/java/io/kadai/spi/history/internal/HistoryEventManager.java:75]: To have the class of the event in the log message.

File: lib/kadai-core/src/main/java/io/kadai/spi/history/internal/HistoryEventManager.java (hunk 9 above)
Comment (CRoberto1926) [reply lib/kadai-core/src/main/java/io/kadai/spi/history/internal/HistoryEventManager.java:65]: To have the class of the event in the log message.

File: lib/kadai-core/src/main/java/io/kadai/spi/history/internal/HistoryEventManager.java (hunk 10 above)
Comment (CRoberto1926) [reply lib/kadai-core/src/main/java/io/kadai/spi/history/internal/HistoryEventManager.java:57]: To have the class of the event in the log message.

File: lib/kadai-core/src/main/java/io/kadai/task/internal/models/TaskImpl.java (hunk 11 above)
Comment (CRoberto1926) [reply lib/kadai-core/src/main/java/io/kadai/task/internal/models/TaskImpl.java:320]: Is it really necessary to discuss such a small detail?

File: lib/kadai-core/src/main/java/io/kadai/user/internal/UserServiceImpl.java (hunk 12 above)
Comment (CRoberto1926) [reply lib/kadai-core/src/main/java/io/kadai/user/internal/UserServiceImpl.java:168]: Because id comes directly from the REST layer without any sort of validation. Since `getUser(id)` is call to validate that the user exists, it is better to use the id from the retrieved object, than to directly use something that comes from the REST layer. And since `getUser(id)` was already called, there are no additional instructions executed.

File: lib/kadai-core/src/test/java/acceptance/jobs/JobRunnerAccTest.java (hunk 13 above)
Comment (CRoberto1926) [reply lib/kadai-core/src/test/java/acceptance/jobs/JobRunnerAccTest.java:79]: It is not relevant, because it refers to code that was commented out since 08.2021

File: lib/kadai-core/src/test/java/acceptance/task/query/QueryTasksAccTest.java (hunk 14 above)
Comment (CRoberto1926) [reply lib/kadai-core/src/test/java/acceptance/task/query/QueryTasksAccTest.java]: IntelliJ changed it automatically because CUSTOM_7 is already static imported for lines 544 and 552. What is the preferred solution here?

File: lib/kadai-core/src/test/java/acceptance/task/query/QueryTasksAccTest.java (hunk 15 above)
Comment (CRoberto1926) [reply lib/kadai-core/src/test/java/acceptance/task/query/QueryTasksAccTest.java]: IntelliJ changed it automatically because CUSTOM_7 is already static imported for lines 544 and 552. What is the preferred solution here?

File: lib/kadai-core/src/test/java/acceptance/task/update/UpdateTaskAttachmentWithWorkingDaysCalculationAccTest.java (hunk 16 above)
Comment (CRoberto1926) [reply lib/kadai-core/src/test/java/acceptance/task/update/UpdateTaskAttachmentWithWorkingDaysCalculationAccTest.java]: Because it is the same name as the class property, and it was a SonarCloud issue

File: rest/kadai-rest-spring/src/main/java/io/kadai/task/rest/assembler/AttachmentRepresentationModelAssembler.java (hunk 17 above)
Comment (CRoberto1926) [reply rest/kadai-rest-spring/src/main/java/io/kadai/task/rest/assembler/AttachmentRepresentationModelAssembler.java:68]: Because I deleted the class AttachmentController, which is completely empty and without annotations

File: rest/kadai-rest-spring-example-wildfly/src/test/java/io/kadai/example/wildfly/KadaiWildflyWithHistoryLoggerEnabledTest.java (hunk 18 above)
Comment (CRoberto1926) [reply rest/kadai-rest-spring-example-wildfly/src/test/java/io/kadai/example/wildfly/KadaiWildflyWithHistoryLoggerEnabledTest.java:64]: I don't know, but they were not used. Maybe a copy paste error?

File: lib/kadai-core/src/test/java/acceptance/task/query/QueryTasksAccTest.java (hunk 14 above)
Comment (ryzheboka) [reply lib/kadai-core/src/test/java/acceptance/task/query/QueryTasksAccTest.java]: It's easier to read if all TaskCustomFields are used in the same way. Would you agree on keeping TaskCustomField.CUSTOM_7 ?

File: lib/kadai-core/src/test/java/acceptance/task/update/UpdateTaskAttachmentWithWorkingDaysCalculationAccTest.java (hunk 16 above)
Comment (ryzheboka) [reply lib/kadai-core/src/test/java/acceptance/task/update/UpdateTaskAttachmentWithWorkingDaysCalculationAccTest.java]: What do you think about exclusing the issue from SonarCloud instead of changing the variable? Because we have the type AttachmentImpl, it makes the variable name confusing

**Review by ryzheboka — APPROVED** [review]
