### PR TITLE
Closes #45 - global handlers for most-specific exceptions & fine-grained logging 

### LINKED ISSUE #45: Unnecessarily printed stacktraces in REST API
TODO: We have to try first if we can shorten the error

It would be better not to print the full stacktrace in precise error case

2023-03-24T08:56:37.5119304Z 2023-03-24 08:56:37.482 ERROR 1876 --- [-auto-52-exec-1] p.t.c.rest.TaskanaRestExceptionHandler : Error occurred during processing of rest request: ExceptionRepresentationModel [error=ErrorCode [key=CLASSIFICATION_WITH_ID_NOT_FOUND, messageVariables={classificationId=CLI:200000000000000000000000000000000004}], status=404, exception=pro.taskana.classification.api.exceptions.ClassificationNotFoundException, message=Classification with id 'CLI:200000000000000000000000000000000004' wasn't found, path=/api/v1/classifications/CLI:200000000000000000000000000000000004]
2023-03-24T08:56:37.5120804Z
2023-03-24T08:56:37.5121963Z pro.taskana.classification.api.exceptions.ClassificationNotFoundException: Classification with id 'CLI:200000000000000000000000000000000004' wasn't found
2023-03-24T08:56:37.5123737Z at pro.taskana.classification.internal.ClassificationServiceImpl.getClassification(ClassificationServiceImpl.java:100) ~[taskana-core-6.0.2.jar:6.0.2]
2023-03-24T08:56:37.5125181Z at pro.taskana.classification.rest.ClassificationController.getClassification(ClassificationController.java:110) ~[classes/:na]
2023-03-24T08:56:37.5126239Z at pro.taskana.classification.rest.ClassificationController$$FastClassBySpringCGLIB$$80c77314.invoke() ~[classes/:na]
2023-03-24T08:56:37.5127731Z at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.25.jar:5.3.25]

### PR DESCRIPTION
**Pull request by bruderj15**
The Quality-Gate fails due to test-coverage.
However, unit-testing a global exception handler seems useless as integration with controllers is key.
Therefore, adding tests for exception handling in controllers acceptance- and integrationtests should be considered.

### Thanks for your PR! Please fill out the following list :)

---

- [x] I put the ticket or multiple tickets in review
- [x] Commit message format → Closes #&lt;Issue Number&gt; - Your commit message.
- [x] Sonarcloud link : Not available, Quality-Gate can be seen in CI: https://github.com/bruderj15/kadai-fork/runs/36345898177
- [x] No documentation update needed
- [ ] Link to PR with documentation update: \<add the link here>
- [x] No Release Notes needed
- [ ] Release Notes :

```

```

### CODE REVIEW

File: rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java [hunk 1]
```diff
@@ -215,15 +342,23 @@ protected ResponseEntity<Object> handleMethodArgumentNotValid(
...
+  private ResponseEntity<Object> handle(
       ErrorCode errorCode, Throwable ex, WebRequest req, HttpStatus status) {
-    ExceptionRepresentationModel errorData =
+    final ExceptionRepresentationModel errorData =
         new ExceptionRepresentationModel(errorCode, status, ex, req);
-    logger.error(
-        String.format("Error occurred during processing of rest request: %s", errorData), ex);
+
+    switch (status.series()) {
+      case CLIENT_ERROR -> logger.warn(
```
Comment (CRoberto1926) [inline rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java:354]: I think this should be an error and not a warn

File: rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java [hunk 2]
```diff
@@ -215,15 +342,23 @@ protected ResponseEntity<Object> handleMethodArgumentNotValid(
...
+          String.format("Exception thrown during processing of rest request: %s", errorData));
+      case SERVER_ERROR -> logger.error(
+          String.format("Error occurred during processing of rest request: %s", errorData), ex);
+      default -> logger.warn(
```
Comment (CRoberto1926) [inline rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java:358]: I think this should be an error and not a warn

File: rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java [hunk 3]
```diff
@@ -76,125 +75,253 @@
...
   @ExceptionHandler(Exception.class)
   protected ResponseEntity<Object> handleGeneralException(Exception ex, WebRequest req) {
-    return buildResponse(
-        ErrorCode.of(ERROR_KEY_UNKNOWN_ERROR), ex, req, HttpStatus.INTERNAL_SERVER_ERROR);
+    ExceptionRepresentationModel errorData =
+        new ExceptionRepresentationModel(
+            ErrorCode.of(ERROR_KEY_UNKNOWN_ERROR), HttpStatus.INTERNAL_SERVER_ERROR, ex, req);
+    logger.error(
+        String.format("Unknown error occurred during processing of rest request: %s", errorData),
+        ex);
```
Comment (CRoberto1926) [inline rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java:320]: Do we want to log this stacktrace?

**Review by CRoberto1926 — COMMENTED** [review]
Did you briefly test with frontend?

File: rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java (hunk 1 above)
Comment (bruderj15) [reply rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java:354]: I strongly disagree.
Consider a client trying to request an endpoint not existing.
Is this an error? No. Errors are states intended never to be reached.

Contrarily, one could even argue if this is even worth a warning. 
Many people do log it informational.

File: rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java (hunk 3 above)
Comment (bruderj15) [reply rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java:320]: Yes, as it points to us failing to provide a specific handler for an exception, indicating missing thoughts around the implementation.
The question then is, which implementation and where?
The stack trace answers immediately.

Take into perspective that this does not pollute the logs, because we should always handle the most-specific exceptions.

File: rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java (hunk 2 above)
Comment (bruderj15) [reply rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java:358]: Making this an error would contradict the semantics of the HTTP codes.
It cannot be 4xx nor 5xx because those are checked already.

Therefore it must be either 1xx, 2xx or 3xx, which none of indicate faulty behaviour.

**Comment by bruderj15** [comment]
> Did you briefly test with frontend?

No, semantics shall not change with this PR and all tests passed.
Manually testing would undermine the relevance of the automated tests.

File: rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java (hunk 1 above)
Comment (CRoberto1926) [reply rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java:354]: Well, I strongly disagree about exceptions not logged as errors ;) but your argument is valid. Warning may be fine

File: rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java (hunk 2 above)
Comment (CRoberto1926) [reply rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java:358]: you`re right

File: rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java (hunk 3 above)
Comment (CRoberto1926) [reply rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java:320]: ok

**Comment by CRoberto1926** [comment]
> > Did you briefly test with frontend?
> 
> No, semantics shall not change with this PR and all tests passed. Manually testing would undermine the relevance of the automated tests.

I don't think manually testing undermines anything :)

**Comment by bruderj15** [comment]
> > > Did you briefly test with frontend?
> > 
> > 
> > No, semantics shall not change with this PR and all tests passed. Manually testing would undermine the relevance of the automated tests.
> 
> I don't think manually testing undermines anything :)

I briefly shared the thought and tested locally, no issues.

**Review by CRoberto1926 — APPROVED** [review]
