### PR TITLE
Closes #954 - Fix querying actual max schema version

### LINKED ISSUE #954: Database schema version check does not work properly
If the schema version is valid is checked with this SQL statement:

https://github.com/kadai-io/kadai/blob/1d560e5588270f8eb0cde2c1c42f3dc320f4e102/common/kadai-common/src/main/java/io/kadai/common/internal/configuration/DbSchemaCreator.java#L101-L103

The issue is that VERSION is a varchar, so the max function does not work as expected. If I have 9.0.0 and 10.0.0 as values in the column, the output is 9.0.0.

### PR DESCRIPTION
**Pull request by bruderj15**
## Definition of Done

- [x] The corresponding ticket is in state `In Review`
- [x] The corresponding ticket is attached to this Pull-Request
- [x] The commit-message-format `Closes #ISSUE_ID - PROBLEM/SOLUTION` 
  - is present as single-commit already or
  - will be squashed on merge
- [x] The changes pass the SonarQubeCloud-Quality-Gate
- [x] If the documentation needs an update, following there's a link to it:

### CODE REVIEW

**Review by jamesrdi — APPROVED** [review]

File: common/kadai-common/src/main/java/io/kadai/common/internal/configuration/DbSchemaCreator.java [hunk 1]
```diff
@@ -137,6 +153,10 @@ public void setDataSource(DataSource dataSource) {
     this.dataSource = dataSource;
   }
 
+  public String getSchemaName() {
```
Comment (leantios) [inline common/kadai-common/src/main/java/io/kadai/common/internal/configuration/DbSchemaCreator.java:156]: Why did you add the getter here?

**Review by leantios — COMMENTED** [review]
Nice solution using ComparableVersion!

File: common/kadai-common/src/main/java/io/kadai/common/internal/configuration/DbSchemaCreator.java (hunk 1 above)
Comment (bruderj15) [reply common/kadai-common/src/main/java/io/kadai/common/internal/configuration/DbSchemaCreator.java:156]: Needed it for the test [here](https://github.com/kadai-io/kadai/pull/959/files#diff-9809786ac7aef01e70740bccff71e09a5727e3a03e806d5706ee529ce3fe9e7aR66)

Comment (leantios) [reply common/kadai-common/src/main/java/io/kadai/common/internal/configuration/DbSchemaCreator.java:156]: Can you not just use "KADAI"?

Comment (bruderj15) [reply common/kadai-common/src/main/java/io/kadai/common/internal/configuration/DbSchemaCreator.java:156]: Behavior is coupled to `DbSchemaCreator::schemaName`.
As it might change in the future I went for the getter.

Comment (leantios) [reply common/kadai-common/src/main/java/io/kadai/common/internal/configuration/DbSchemaCreator.java:156]: But you set the schema name yourself three lines before, no? Anyway now it's merged

Comment (leantios) [reply common/kadai-common/src/main/java/io/kadai/common/internal/configuration/DbSchemaCreator.java:156]: I mean three lines before you access getSchemaName in the test

Comment (bruderj15) [reply common/kadai-common/src/main/java/io/kadai/common/internal/configuration/DbSchemaCreator.java:156]: I see!
Hideous crime!

I only aided and abetted the crime by moving the code
