### PR TITLE
Closes #1196 - Unify Persistence-Layer-Access to one DAO per Entity

### LINKED ISSUE #1196: Unify Persistence-Layer-Access to one DAO per Entity
Follow-Up to #915 

## Description

In general, CRUD-Applications restrict access to the persistence-layer to at most one DAO per entity.
Using MyBatis as Persistence-Framework, our DAO is the `Mapper`, e.g. `TaskMapper`.
Throughout the code-base this is done for most parts.

However, there are exceptions where some classes access the persistence-layer - bypassing the DAO.
This ships with unnecessary complexity and scatters the access to the persistence-layer.

Therefore, unify the access by moving all access to the respective DAOs.

(Query-Mappers are an exception here, do not touch them)

## Definition of Done

- [x] Checked for all occurences of non-DAO persistence-access
- [x] Moved all persistence-access to the respective DAOs

### PR DESCRIPTION
**Pull request by bruderj15**
Did not adjust [`TaskUpdatePriorityBatchStatement`](https://github.com/kadai-io/kadai/blob/master/lib/kadai-core/src/main/java/io/kadai/task/internal/jobs/helper/TaskUpdatePriorityBatchStatement.java#L35) because MyBatis has no configuration-driven way to execute batch-statements.

I did not want to use dynamic `<foreach>...` for the task-priority updates as this would be much more expensive than manual batching.
As caches won't be used anyways  and the importance of this ticket is degarded, we're fine with the little scattering of the data-access-layer.

## Definition of Done

- [x] The corresponding ticket is in state `In Review`
- [x] The corresponding ticket is attached to this Pull-Request
- [x] The commit-message-format `Closes #ISSUE_ID - PROBLEM/SOLUTION` 
  - is present as single-commit already or
  - will be squashed on merge
- [x] The changes pass the SonarQubeCloud-Quality-Gate
- [x] If the documentation needs an update, following there's a link to it:
- [x] If extra release-notes are required, they're listed indented below:

### CODE REVIEW

File: rest/kadai-rest-spring/src/main/java/io/kadai/user/jobs/UserInfoRefreshJob.java [hunk 1]
```diff
@@ -91,24 +88,17 @@ protected void execute() {
     }
   }
 
-  private void clearExistingUsersAndGroupsAndPermissions() {
+  private void clearExistingUsersAndGroupsAndPermissions() throws NotAuthorizedException {
+    if (LOGGER.isDebugEnabled()) {
```
Comment (CRoberto1926) [inline rest/kadai-rest-spring/src/main/java/io/kadai/user/jobs/UserInfoRefreshJob.java:92]: I think you can delete this guard and the guard on line 99. There is no String Parsing in the LOGGER, so no performance impairements.

**Review by CRoberto1926 — COMMENTED** [review]
LGTM

File: rest/kadai-rest-spring/src/main/java/io/kadai/user/jobs/UserInfoRefreshJob.java (hunk 1 above)
Comment (bruderj15) [reply rest/kadai-rest-spring/src/main/java/io/kadai/user/jobs/UserInfoRefreshJob.java:92]: Afaik the log is still produced (sent to the Log-Manager) and just trashed there.
We have usages like here throughout the codebase very often.

I personally do not like it either and would pay the minimal (and certainly negligible) performance-price for readability.
To keep it consistent across the code-base, I'll leave it like this for now.

**Review by CRoberto1926 — APPROVED** [review]
