### PR TITLE
Closes #285 - Fix usage of permissionNameAttribute

### LINKED ISSUE #285: Fix usage of kadai.ldap.permissionNameAttribute

### PR DESCRIPTION
**Pull request by ryzheboka**
### Thanks for your PR! Please fill out the following list :)

---

- [x] I put the ticket or multiple tickets in review
- [x] Commit message format → Closes #&lt;Issue Number&gt; - Your commit message.
- [ ] Sonarcloud link : \<add the link here>
- [ ] No documentation update needed
- [ ] Link to PR with documentation update: https://github.com/kadai-io/kadai-doc/pull/37
- [x] No Release Notes needed
- [ ] Release Notes :

```

```

### CODE REVIEW

File: rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/ldap/LdapClient.java [hunk 1]
```diff
@@ -384,11 +384,11 @@ public List<AccessIdRepresentationModel> searchPermissionsAccessIdHas(final Stri
     }
     orFilter.or(new EqualsFilter(getPermissionsOfUserName(), dn));
     final AndFilter andFilter2 = new AndFilter();
-    andFilter2.and(new PresentFilter(getUserPermissionsAttribute()));
+    andFilter2.and(new PresentFilter(getPermissionNameAttribute()));
     andFilter.and(orFilter);
     andFilter2.and(andFilter);
 
-    String[] userAttributesToReturn = {getUserIdAttribute(), getUserPermissionsAttribute()};
+    String[] userAttributesToReturn = {getUserIdAttribute(), getPermissionNameAttribute()};
```
Comment (holgerhagen) [inline rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/ldap/LdapClient.java]: here

**Review by holgerhagen — CHANGES_REQUESTED** [review]

File: rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/ldap/LdapClient.java (hunk 1 above)
Comment (ryzheboka) [reply rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/ldap/LdapClient.java]: We checked it and changed the variable name to make more sense

**Review by holgerhagen — APPROVED** [review]
